/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ru.psavinov.liferay.langlearn.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LLSettings service. Represents a row in the &quot;LangLearn_LLSettings&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ru.psavinov.liferay.langlearn.model.impl.LLSettingsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ru.psavinov.liferay.langlearn.model.impl.LLSettingsImpl}.
 * </p>
 *
 * @author Pavel Savinov
 * @see LLSettings
 * @see ru.psavinov.liferay.langlearn.model.impl.LLSettingsImpl
 * @see ru.psavinov.liferay.langlearn.model.impl.LLSettingsModelImpl
 * @generated
 */
public interface LLSettingsModel extends AuditedModel, BaseModel<LLSettings> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a LangLearnSettings model instance should use the {@link LLSettings} interface instead.
	 */

	/**
	 * Returns the primary key of this LangLearnSettings.
	 *
	 * @return the primary key of this LangLearnSettings
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this LangLearnSettings.
	 *
	 * @param primaryKey the primary key of this LangLearnSettings
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the settings ID of this LangLearnSettings.
	 *
	 * @return the settings ID of this LangLearnSettings
	 */
	public long getSettingsId();

	/**
	 * Sets the settings ID of this LangLearnSettings.
	 *
	 * @param settingsId the settings ID of this LangLearnSettings
	 */
	public void setSettingsId(long settingsId);

	/**
	 * Returns the locale from of this LangLearnSettings.
	 *
	 * @return the locale from of this LangLearnSettings
	 */
	@AutoEscape
	public String getLocaleFrom();

	/**
	 * Sets the locale from of this LangLearnSettings.
	 *
	 * @param localeFrom the locale from of this LangLearnSettings
	 */
	public void setLocaleFrom(String localeFrom);

	/**
	 * Returns the locale to of this LangLearnSettings.
	 *
	 * @return the locale to of this LangLearnSettings
	 */
	@AutoEscape
	public String getLocaleTo();

	/**
	 * Sets the locale to of this LangLearnSettings.
	 *
	 * @param localeTo the locale to of this LangLearnSettings
	 */
	public void setLocaleTo(String localeTo);

	/**
	 * Returns the words per day of this LangLearnSettings.
	 *
	 * @return the words per day of this LangLearnSettings
	 */
	public int getWordsPerDay();

	/**
	 * Sets the words per day of this LangLearnSettings.
	 *
	 * @param wordsPerDay the words per day of this LangLearnSettings
	 */
	public void setWordsPerDay(int wordsPerDay);

	/**
	 * Returns the mode of this LangLearnSettings.
	 *
	 * @return the mode of this LangLearnSettings
	 */
	public int getMode();

	/**
	 * Sets the mode of this LangLearnSettings.
	 *
	 * @param mode the mode of this LangLearnSettings
	 */
	public void setMode(int mode);

	/**
	 * Returns the company ID of this LangLearnSettings.
	 *
	 * @return the company ID of this LangLearnSettings
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this LangLearnSettings.
	 *
	 * @param companyId the company ID of this LangLearnSettings
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this LangLearnSettings.
	 *
	 * @return the user ID of this LangLearnSettings
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this LangLearnSettings.
	 *
	 * @param userId the user ID of this LangLearnSettings
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this LangLearnSettings.
	 *
	 * @return the user uuid of this LangLearnSettings
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this LangLearnSettings.
	 *
	 * @param userUuid the user uuid of this LangLearnSettings
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this LangLearnSettings.
	 *
	 * @return the user name of this LangLearnSettings
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this LangLearnSettings.
	 *
	 * @param userName the user name of this LangLearnSettings
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this LangLearnSettings.
	 *
	 * @return the create date of this LangLearnSettings
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this LangLearnSettings.
	 *
	 * @param createDate the create date of this LangLearnSettings
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this LangLearnSettings.
	 *
	 * @return the modified date of this LangLearnSettings
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this LangLearnSettings.
	 *
	 * @param modifiedDate the modified date of this LangLearnSettings
	 */
	public void setModifiedDate(Date modifiedDate);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(LLSettings llSettings);

	public int hashCode();

	public CacheModel<LLSettings> toCacheModel();

	public LLSettings toEscapedModel();

	public String toString();

	public String toXmlString();
}