/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ru.psavinov.liferay.langlearn.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LLWordPair service. Represents a row in the &quot;LangLearn_LLWordPair&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ru.psavinov.liferay.langlearn.model.impl.LLWordPairModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ru.psavinov.liferay.langlearn.model.impl.LLWordPairImpl}.
 * </p>
 *
 * @author Pavel Savinov
 * @see LLWordPair
 * @see ru.psavinov.liferay.langlearn.model.impl.LLWordPairImpl
 * @see ru.psavinov.liferay.langlearn.model.impl.LLWordPairModelImpl
 * @generated
 */
public interface LLWordPairModel extends AuditedModel, BaseModel<LLWordPair> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a LangLearnWordPair model instance should use the {@link LLWordPair} interface instead.
	 */

	/**
	 * Returns the primary key of this LangLearnWordPair.
	 *
	 * @return the primary key of this LangLearnWordPair
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this LangLearnWordPair.
	 *
	 * @param primaryKey the primary key of this LangLearnWordPair
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the word pair ID of this LangLearnWordPair.
	 *
	 * @return the word pair ID of this LangLearnWordPair
	 */
	public long getWordPairId();

	/**
	 * Sets the word pair ID of this LangLearnWordPair.
	 *
	 * @param wordPairId the word pair ID of this LangLearnWordPair
	 */
	public void setWordPairId(long wordPairId);

	/**
	 * Returns the word from ID of this LangLearnWordPair.
	 *
	 * @return the word from ID of this LangLearnWordPair
	 */
	public long getWordFromId();

	/**
	 * Sets the word from ID of this LangLearnWordPair.
	 *
	 * @param wordFromId the word from ID of this LangLearnWordPair
	 */
	public void setWordFromId(long wordFromId);

	/**
	 * Returns the word to ID of this LangLearnWordPair.
	 *
	 * @return the word to ID of this LangLearnWordPair
	 */
	public long getWordToId();

	/**
	 * Sets the word to ID of this LangLearnWordPair.
	 *
	 * @param wordToId the word to ID of this LangLearnWordPair
	 */
	public void setWordToId(long wordToId);

	/**
	 * Returns the company ID of this LangLearnWordPair.
	 *
	 * @return the company ID of this LangLearnWordPair
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this LangLearnWordPair.
	 *
	 * @param companyId the company ID of this LangLearnWordPair
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this LangLearnWordPair.
	 *
	 * @return the user ID of this LangLearnWordPair
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this LangLearnWordPair.
	 *
	 * @param userId the user ID of this LangLearnWordPair
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this LangLearnWordPair.
	 *
	 * @return the user uuid of this LangLearnWordPair
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this LangLearnWordPair.
	 *
	 * @param userUuid the user uuid of this LangLearnWordPair
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this LangLearnWordPair.
	 *
	 * @return the user name of this LangLearnWordPair
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this LangLearnWordPair.
	 *
	 * @param userName the user name of this LangLearnWordPair
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this LangLearnWordPair.
	 *
	 * @return the create date of this LangLearnWordPair
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this LangLearnWordPair.
	 *
	 * @param createDate the create date of this LangLearnWordPair
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this LangLearnWordPair.
	 *
	 * @return the modified date of this LangLearnWordPair
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this LangLearnWordPair.
	 *
	 * @param modifiedDate the modified date of this LangLearnWordPair
	 */
	public void setModifiedDate(Date modifiedDate);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(LLWordPair llWordPair);

	public int hashCode();

	public CacheModel<LLWordPair> toCacheModel();

	public LLWordPair toEscapedModel();

	public String toString();

	public String toXmlString();
}