/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ru.psavinov.liferay.langlearn.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import ru.psavinov.liferay.langlearn.model.LLWordPair;
import ru.psavinov.liferay.langlearn.service.LLSettingsLocalService;
import ru.psavinov.liferay.langlearn.service.LLSettingsService;
import ru.psavinov.liferay.langlearn.service.LLStatLocalService;
import ru.psavinov.liferay.langlearn.service.LLStatService;
import ru.psavinov.liferay.langlearn.service.LLWordLocalService;
import ru.psavinov.liferay.langlearn.service.LLWordPairLocalService;
import ru.psavinov.liferay.langlearn.service.LLWordPairService;
import ru.psavinov.liferay.langlearn.service.LLWordService;
import ru.psavinov.liferay.langlearn.service.persistence.LLSettingsPersistence;
import ru.psavinov.liferay.langlearn.service.persistence.LLStatPersistence;
import ru.psavinov.liferay.langlearn.service.persistence.LLWordPairPersistence;
import ru.psavinov.liferay.langlearn.service.persistence.LLWordPersistence;

import javax.sql.DataSource;

/**
 * The base implementation of the LangLearnWordPair remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link ru.psavinov.liferay.langlearn.service.impl.LLWordPairServiceImpl}.
 * </p>
 *
 * @author Pavel Savinov
 * @see ru.psavinov.liferay.langlearn.service.impl.LLWordPairServiceImpl
 * @see ru.psavinov.liferay.langlearn.service.LLWordPairServiceUtil
 * @generated
 */
public abstract class LLWordPairServiceBaseImpl extends BaseServiceImpl
	implements LLWordPairService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link ru.psavinov.liferay.langlearn.service.LLWordPairServiceUtil} to access the LangLearnWordPair remote service.
	 */

	/**
	 * Returns the LangLearnSettings local service.
	 *
	 * @return the LangLearnSettings local service
	 */
	public LLSettingsLocalService getLLSettingsLocalService() {
		return llSettingsLocalService;
	}

	/**
	 * Sets the LangLearnSettings local service.
	 *
	 * @param llSettingsLocalService the LangLearnSettings local service
	 */
	public void setLLSettingsLocalService(
		LLSettingsLocalService llSettingsLocalService) {
		this.llSettingsLocalService = llSettingsLocalService;
	}

	/**
	 * Returns the LangLearnSettings remote service.
	 *
	 * @return the LangLearnSettings remote service
	 */
	public LLSettingsService getLLSettingsService() {
		return llSettingsService;
	}

	/**
	 * Sets the LangLearnSettings remote service.
	 *
	 * @param llSettingsService the LangLearnSettings remote service
	 */
	public void setLLSettingsService(LLSettingsService llSettingsService) {
		this.llSettingsService = llSettingsService;
	}

	/**
	 * Returns the LangLearnSettings persistence.
	 *
	 * @return the LangLearnSettings persistence
	 */
	public LLSettingsPersistence getLLSettingsPersistence() {
		return llSettingsPersistence;
	}

	/**
	 * Sets the LangLearnSettings persistence.
	 *
	 * @param llSettingsPersistence the LangLearnSettings persistence
	 */
	public void setLLSettingsPersistence(
		LLSettingsPersistence llSettingsPersistence) {
		this.llSettingsPersistence = llSettingsPersistence;
	}

	/**
	 * Returns the LangLearnStatistics local service.
	 *
	 * @return the LangLearnStatistics local service
	 */
	public LLStatLocalService getLLStatLocalService() {
		return llStatLocalService;
	}

	/**
	 * Sets the LangLearnStatistics local service.
	 *
	 * @param llStatLocalService the LangLearnStatistics local service
	 */
	public void setLLStatLocalService(LLStatLocalService llStatLocalService) {
		this.llStatLocalService = llStatLocalService;
	}

	/**
	 * Returns the LangLearnStatistics remote service.
	 *
	 * @return the LangLearnStatistics remote service
	 */
	public LLStatService getLLStatService() {
		return llStatService;
	}

	/**
	 * Sets the LangLearnStatistics remote service.
	 *
	 * @param llStatService the LangLearnStatistics remote service
	 */
	public void setLLStatService(LLStatService llStatService) {
		this.llStatService = llStatService;
	}

	/**
	 * Returns the LangLearnStatistics persistence.
	 *
	 * @return the LangLearnStatistics persistence
	 */
	public LLStatPersistence getLLStatPersistence() {
		return llStatPersistence;
	}

	/**
	 * Sets the LangLearnStatistics persistence.
	 *
	 * @param llStatPersistence the LangLearnStatistics persistence
	 */
	public void setLLStatPersistence(LLStatPersistence llStatPersistence) {
		this.llStatPersistence = llStatPersistence;
	}

	/**
	 * Returns the LangLeardWord local service.
	 *
	 * @return the LangLeardWord local service
	 */
	public LLWordLocalService getLLWordLocalService() {
		return llWordLocalService;
	}

	/**
	 * Sets the LangLeardWord local service.
	 *
	 * @param llWordLocalService the LangLeardWord local service
	 */
	public void setLLWordLocalService(LLWordLocalService llWordLocalService) {
		this.llWordLocalService = llWordLocalService;
	}

	/**
	 * Returns the LangLeardWord remote service.
	 *
	 * @return the LangLeardWord remote service
	 */
	public LLWordService getLLWordService() {
		return llWordService;
	}

	/**
	 * Sets the LangLeardWord remote service.
	 *
	 * @param llWordService the LangLeardWord remote service
	 */
	public void setLLWordService(LLWordService llWordService) {
		this.llWordService = llWordService;
	}

	/**
	 * Returns the LangLeardWord persistence.
	 *
	 * @return the LangLeardWord persistence
	 */
	public LLWordPersistence getLLWordPersistence() {
		return llWordPersistence;
	}

	/**
	 * Sets the LangLeardWord persistence.
	 *
	 * @param llWordPersistence the LangLeardWord persistence
	 */
	public void setLLWordPersistence(LLWordPersistence llWordPersistence) {
		this.llWordPersistence = llWordPersistence;
	}

	/**
	 * Returns the LangLearnWordPair local service.
	 *
	 * @return the LangLearnWordPair local service
	 */
	public LLWordPairLocalService getLLWordPairLocalService() {
		return llWordPairLocalService;
	}

	/**
	 * Sets the LangLearnWordPair local service.
	 *
	 * @param llWordPairLocalService the LangLearnWordPair local service
	 */
	public void setLLWordPairLocalService(
		LLWordPairLocalService llWordPairLocalService) {
		this.llWordPairLocalService = llWordPairLocalService;
	}

	/**
	 * Returns the LangLearnWordPair remote service.
	 *
	 * @return the LangLearnWordPair remote service
	 */
	public LLWordPairService getLLWordPairService() {
		return llWordPairService;
	}

	/**
	 * Sets the LangLearnWordPair remote service.
	 *
	 * @param llWordPairService the LangLearnWordPair remote service
	 */
	public void setLLWordPairService(LLWordPairService llWordPairService) {
		this.llWordPairService = llWordPairService;
	}

	/**
	 * Returns the LangLearnWordPair persistence.
	 *
	 * @return the LangLearnWordPair persistence
	 */
	public LLWordPairPersistence getLLWordPairPersistence() {
		return llWordPairPersistence;
	}

	/**
	 * Sets the LangLearnWordPair persistence.
	 *
	 * @param llWordPairPersistence the LangLearnWordPair persistence
	 */
	public void setLLWordPairPersistence(
		LLWordPairPersistence llWordPairPersistence) {
		this.llWordPairPersistence = llWordPairPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
	}

	protected Class<?> getModelClass() {
		return LLWordPair.class;
	}

	protected String getModelClassName() {
		return LLWordPair.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = llWordPairPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = LLSettingsLocalService.class)
	protected LLSettingsLocalService llSettingsLocalService;
	@BeanReference(type = LLSettingsService.class)
	protected LLSettingsService llSettingsService;
	@BeanReference(type = LLSettingsPersistence.class)
	protected LLSettingsPersistence llSettingsPersistence;
	@BeanReference(type = LLStatLocalService.class)
	protected LLStatLocalService llStatLocalService;
	@BeanReference(type = LLStatService.class)
	protected LLStatService llStatService;
	@BeanReference(type = LLStatPersistence.class)
	protected LLStatPersistence llStatPersistence;
	@BeanReference(type = LLWordLocalService.class)
	protected LLWordLocalService llWordLocalService;
	@BeanReference(type = LLWordService.class)
	protected LLWordService llWordService;
	@BeanReference(type = LLWordPersistence.class)
	protected LLWordPersistence llWordPersistence;
	@BeanReference(type = LLWordPairLocalService.class)
	protected LLWordPairLocalService llWordPairLocalService;
	@BeanReference(type = LLWordPairService.class)
	protected LLWordPairService llWordPairService;
	@BeanReference(type = LLWordPairPersistence.class)
	protected LLWordPairPersistence llWordPairPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private LLWordPairServiceClpInvoker _clpInvoker = new LLWordPairServiceClpInvoker();
}